language: generic

install: false

addons:
  ssh_known_hosts:
    - origin-www.scandalsrfc.org
    - origin-test.scandalsrfc.org

before_install:
  - openssl aes-256-cbc -K $encrypted_725fb8bd8d22_key -iv $encrypted_725fb8bd8d22_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after $TRAVIS_BUILD_DIR/ deploy@origin-www.scandalsrfc.org:/var/www/html/www-scandalsrfc-org
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: rsync -r --delete-after $TRAVIS_BUILD_DIR/ deploy@origin-test.scandalsrfc.org:/var/www/html/test-scandalsrfc-org
    on:
      branch: develop
