language: generic

addons:
  ssh_known_hosts:
    - 138.197.48.54

before_install:
  - openssl aes-256-cbc -K $encrypted_725fb8bd8d22_key -iv $encrypted_725fb8bd8d22_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa

deploy:
  - provider: script
    skip_cleanup: true
    script: "rsync -v -r --delete-after --exclude '.git*' --exclude '*.enc' --exclude '.travis.*' $TRAVIS_BUILD_DIR/ deploy@138.197.48.54:/var/www/www-scandalsrfc-org"
    on:
      branch: master
  - provider: script
    skip_cleanup: true
    script: "rsync -v -r --delete-after --exclude '.git*' --exclude '*.enc' --exclude '.travis.*' $TRAVIS_BUILD_DIR/ deploy@138.197.48.54:/var/www/test-scandalsrfc-org"
    on:
      branch: develop
